config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true


end

app/models/plan.rb
class Plan < ActiveRecord::Base



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  #GET request to /contact-us and show new form
  def new
    @contact = Contact.new
  end

  #POST request /contact_params
  def create
    #Mass assignment of form fields into contact object
    @contact = Contact.new(contact_params)

    #save contact object to db
    if @contact.save

      #local vars of form fields via parameters
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]

      #plug vars into Contact Mailer email method and send mail
      ContactMailer.contact_email(name, email, body).deliver
      #store success msg
      flash[:success] = "Message sent"
      #redirect to new_contact_path (contact-us)
      redirect_to new_contact_path
    else
      #if it doesnt save to db, store error in flash hash
      flash[:danger] = @contact.errors.full_messages.join(", ")
      #redirect to new_contact_path (contact-us)
      redirect_to new_contact_path
    end

  end

  private
  #to collect data from forms, we need to use strong parameters and whitelist
  # form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="content container">

  <h1 class="text-center">Contact Form</h1>
  <div class="row">

    <div class="offset-md-3 col-md-6">

      <div class="card card-block bg-faded">
        <%= form_for @contact, url: contacts_path, method: 'POST' do |f| %>

        <div class="form-group row">
          <%= f.label :name, 'Name: ', class: 'col-sm-3 col-md-4' %>
          <%= f.text_field :name, class: 'form-control col-sm-9 col-md-8' %>
        </div>

        <div class="form-group row">
          <%= f.label :email, 'Email: ', class: 'col-sm-3 col-md-4' %>
          <%= f.text_field :email, class: 'form-control col-sm-9 col-md-8' %>
        </div>

        <div class="form-group row">
          <%= f.label :comments, 'Comments: ', class: 'col-sm-3 col-md-4' %>
          <%= f.text_area :comments, class: 'form-control col-sm-9 col-md-8' %>
        </div>
        <div class="text-center">

          <%= f.submit 'Submit', class: 'btn btn-default' %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-sm fixed-top navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="container">

        <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-handshake-o "></i>
        DevMatch
        <% end %>

        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">

          <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Contact Us", new_contact_path, class: "nav-link" %>
            </li>

            <% if user_signed_in? %>
            <li class="nav-item mx-2">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
            </li>

          <% else %>
            <li class="nav-item mx-2">
              <%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
            </li>

            <li class="nav-item mx-2">
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
            </li>

            <% end %>
          </ul>

        </div>

      </div>
    </nav>

    <div class="container error-msg">
      <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="content container text-center">

  <h1>About Page</h1>
  <p>We are DevMatch. Our company focuses on creating an exclusive community
  developers and entrepreneurs to meet.</p>

</div>

app/views/pages/home.html.erb
<div class="home-header text-center container-fluid">
  <h1>Welcome to DevMatch</h1>
  <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>